import "./globals.css";
import { Open_Sans } from "next/font/google";
import { CartProvider } from "./ui/cartcontext";
import { WishListProvider } from "./ui/cartcontext";
import Footer from "./ui/footer";
import Navbar from "./ui/navbar";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.className}`}>
        <CartProvider>
          <WishListProvider>
            {/* <Loading/> */}
            <header className="sticky top-0 left-0 z-50"><Navbar/></header>
            {children}
            <footer><Footer/></footer>
          </WishListProvider>
        </CartProvider>
      </body>
    </html>
  );
}
