import "./globals.css";
import { Open_Sans } from "next/font/google";
import Navbar from "./ui/navbar";
import Footer from "./ui/footer";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.className}`}>
        <header><Navbar/></header>
        {children}
        <footer><Footer/></footer>
      </body>
        
    </html>
  );
}
